server.port=8080

# CONFIGURACIÓN ARANGODB OASIS (CLOUD)
arangodb.host=857c16557e9b.arangodb.cloud
arangodb.port=8529
arangodb.user=root
arangodb.password=wPrXkhTYcm7qrdRW29cg
arangodb.database=_system
arangodb.useSsl=true
# Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_dzuH5paum